# Generated by Django 5.1.2 on 2024-11-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
    ]
