# Generated by Django 5.1.2 on 2024-11-13 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0004_remove_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(editable=False, upload_to='product_images/Order_Img'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total',
            field=models.CharField(editable=False, max_length=1000),
        ),
    ]
