# Generated by Django 5.1.2 on 2024-11-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0007_remove_order_amount_order_subtotal_order_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.CharField(default='0.03', max_length=100),
        ),
    ]
