# Generated by Django 5.1.2 on 2024-11-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0008_alter_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seen_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
