# Generated by Django 5.1.2 on 2024-12-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0009_order_seen_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
